# Generated by Django 3.2.11 on 2022-01-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gd', '0002_auto_20220106_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='vedios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio', models.FileField(upload_to='vedios/')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('Add_tags', models.CharField(max_length=300)),
                ('skillcategory', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=500)),
                ('groupskills', models.CharField(max_length=500)),
                ('Targeting_Audience', models.PositiveIntegerField()),
                ('Age_restiction', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_disllikes', models.ManyToManyField(blank=True, related_name='comment_dislkikes', to=settings.AUTH_USER_MODEL)),
                ('comment_likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('vedio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gd.vedios')),
            ],
        ),
    ]
