# Generated by Django 4.0.1 on 2022-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0003_comment_vedios'),
    ]

    operations = [
        migrations.CreateModel(
            name='communitypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createpost', models.ImageField(null=True, upload_to='post/', verbose_name=' ')),
                ('Title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
                ('publish', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('unlist', 'unlist')], default='public', max_length=100)),
            ],
        ),
    ]
