# Generated by Django 4.0.1 on 2022-01-13 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gd', '0004_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='post_likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='community_comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_comment', models.TextField()),
                ('post_created_on', models.DateTimeField(auto_now=True)),
                ('Post_comment_disllikes', models.ManyToManyField(blank=True, related_name='Post_comment_dislkikes', to=settings.AUTH_USER_MODEL)),
                ('Post_comment_likes', models.ManyToManyField(blank=True, related_name='Post_comment_likes', to=settings.AUTH_USER_MODEL)),
                ('community_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='gd.community_comment')),
                ('community_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gd.communitypost')),
            ],
            options={
                'ordering': ['-post_created_on'],
            },
        ),
    ]
