# Generated by Django 3.2.11 on 2022-01-14 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gd', '0005_communitypost_post_likes_alter_communitypost_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_comment',
            old_name='Post_comment_disllikes',
            new_name='comment_disllikes',
        ),
        migrations.RenameField(
            model_name='community_comment',
            old_name='Post_comment_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='community_comment',
            old_name='community_parent',
            new_name='parent',
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_account', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ManyToManyField(blank=True, related_name='block', to='gd.Support')),
                ('followers', models.ManyToManyField(blank=True, related_name='user_follower', to='gd.Support')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='gd.Support')),
                ('pending_reuqest', models.ManyToManyField(blank=True, related_name='pending_request', to='gd.Support')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
