# Generated by Django 3.2.11 on 2022-01-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0006_auto_20220114_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community_comment',
            old_name='community_post',
            new_name='connect',
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=12)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gd.vedios', verbose_name='playlist')),
            ],
        ),
        migrations.CreateModel(
            name='gourpskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gd.groups', verbose_name='groups')),
            ],
        ),
    ]
