# Generated by Django 3.2.11 on 2022-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0009_alter_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
